// <auto-generated />
namespace ThotPlatform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AjoutIdentifiantUniqueEtLangue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjoutIdentifiantUniqueEtLangue));
        
        string IMigrationMetadata.Id
        {
            get { return "202510211900000_AjoutIdentifiantUniqueEtLangue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return null; }
        }
    }
}

